---
- name: Set lxc containers group
  hosts: "{{ container_group | default('all_containers') }}"
  gather_facts: false
  tasks:
    - name: Add hosts to dynamic inventory group
      group_by:
        key: lxc_containers
        parents: all_lxc_containers
      when:
        - container_tech == 'lxc'
  tags:
    - always

- name: Setup Elasticsearch Repo, Install jounrnalbeat and configure
  hosts: all_lxc_containers
  gather_facts: false
  user: root
  handlers:
    - name: Restart journalbeat
      service:
        name: journalbeat
        state: restarted
  tasks:
    - name: Add the repository
      apt_repository:
        repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
        state: present
        update_cache: no
    - name: Add the key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: D27D666CD88E42B4
    - name: Update repositories cache and install journalbeat package
      apt:
        name: journalbeat
        update_cache: yes
    - name: Configure journalbeat
      copy:
        src: journalbeat.yml
        dest: /etc/journalbeat/journalbeat.yml
        owner: root
        group: root
        mode: 0600
      notify:
        - Restart journalbeat
